import {
  calculateCartTotals,
  createCartItem,
  type Address,
  type Cart,
  type CompanyProfile,
  type InvoiceProfile,
  type Order,
  type Product,
  type ProductCategory,
  type ProductSku,
  type Promotion,
  type UserProfile,
} from "./domain";

/**
 * Deterministic fixtures for the first vertical slice.  IDs and SKU codes are
 * deliberately stable so they can be used in links, localStorage and tests.
 */

export const MOCK_CATEGORIES: ProductCategory[] = [
  { id: "precision-parts", name: "精密零件", description: "轴承、联轴器及机械传动件", productCount: 128 },
  { id: "industrial-automation", name: "工业自动化", description: "传感器、控制器与伺服系统", productCount: 86 },
  { id: "electrical-components", name: "电气元件", description: "低压电器、继电器与配电产品", productCount: 94 },
  { id: "tools-and-consumables", name: "工具与耗材", description: "生产现场常用工具和耗材", productCount: 62 },
  { id: "office-and-safety", name: "办公与安全", description: "劳保、办公及仓储用品", productCount: 45 },
];

export const MOCK_COMPANY: CompanyProfile = {
  id: "company-lantu",
  name: "深圳市蓝图精密制造有限公司",
  shortName: "蓝图精密制造",
  taxId: "91440300MA5F8N7X2K",
  customerTier: "gold",
  isVerified: true,
  creditLimit: 1280000,
  creditUsed: 409600,
  paymentTermDays: 30,
  currency: "CNY",
};

export const MOCK_USER: UserProfile = {
  id: "user-lin-yue",
  name: "林悦",
  role: "buyer",
  department: "采购部",
  avatarText: "蓝图",
  companyId: MOCK_COMPANY.id,
};

const SKU_DATE = "2026-09-14T08:00:00.000Z";

function sku(input: Omit<ProductSku, "currency" | "status">): ProductSku {
  return { ...input, currency: "CNY", status: "available" };
}

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-nsk-6205zz",
    slug: "nsk-6205zz",
    title: "NSK 深沟球轴承 6205ZZ",
    subtitle: "日本精工 · 进口原装",
    brand: "NSK",
    categoryId: "precision-parts",
    category: "精密轴承",
    description: "适用于电机、减速机及一般工业传动设备的双面防尘深沟球轴承。",
    unit: "个",
    defaultSkuId: "sku-nsk-6205zz",
    tone: "#e4f4f3",
    accent: "#199d97",
    mark: "NSK",
    badges: ["agreement", "bestseller", "spot"],
    tags: ["轴承", "进口", "深沟球"],
    status: "active",
    isFeatured: true,
    createdAt: "2026-07-02T08:00:00.000Z",
    updatedAt: SKU_DATE,
    skus: [
      sku({
        id: "sku-nsk-6205zz",
        productId: "prod-nsk-6205zz",
        code: "SKU-NSK-6205ZZ",
        name: "6205ZZ / 双面铁盖",
        attributes: { 内径: "25 mm", 外径: "52 mm", 宽度: "15 mm" },
        unit: "个",
        price: 18.6,
        listPrice: 22.4,
        priceTiers: [
          { minQuantity: 1, unitPrice: 18.6, label: "协议价" },
          { minQuantity: 50, unitPrice: 17.48, label: "50+ 阶梯价" },
          { minQuantity: 100, unitPrice: 16.74, label: "100+ 阶梯价" },
        ],
        stock: 2480,
        availability: "in_stock",
        leadTimeLabel: "现货 · 48 小时内发出",
        weightKg: 0.13,
      }),
    ],
  },
  {
    id: "prod-sick-wl12g3",
    slug: "sick-wl12g3",
    title: "SICK 光电传感器 WL12G-3",
    subtitle: "德国西克 · M12 接插件",
    brand: "SICK",
    categoryId: "industrial-automation",
    category: "工业传感器",
    description: "紧凑型漫反射光电传感器，支持稳定的高速物料检测。",
    unit: "件",
    defaultSkuId: "sku-sick-wl12g3",
    tone: "#eaf0fb",
    accent: "#527bc6",
    mark: "SICK",
    badges: ["agreement", "bestseller"],
    tags: ["传感器", "光电", "M12"],
    status: "active",
    isFeatured: true,
    createdAt: "2026-06-18T08:00:00.000Z",
    updatedAt: SKU_DATE,
    skus: [
      sku({
        id: "sku-sick-wl12g3",
        productId: "prod-sick-wl12g3",
        code: "SKU-SICK-WL12G3",
        name: "WL12G-3 · PNP 常开",
        attributes: { 检测距离: "100 mm", 输出: "PNP", 接插件: "M12" },
        unit: "件",
        price: 156,
        listPrice: 179,
        priceTiers: [
          { minQuantity: 1, unitPrice: 156, label: "协议价" },
          { minQuantity: 10, unitPrice: 149.8, label: "10+ 阶梯价" },
          { minQuantity: 30, unitPrice: 143.52, label: "30+ 阶梯价" },
        ],
        stock: 316,
        availability: "low_stock",
        leadTimeLabel: "预计 3–5 个工作日",
        weightKg: 0.08,
      }),
    ],
  },
  {
    id: "prod-yaskawa-sgm7j",
    slug: "yaskawa-sgm7j-04",
    title: "安川 Σ-7 伺服电机 SGM7J",
    subtitle: "400W · 带 20-bit 编码器",
    brand: "YASKAWA",
    categoryId: "industrial-automation",
    category: "伺服电机",
    description: "高响应交流伺服电机，适合精密定位及高速往复运动场景。",
    unit: "台",
    defaultSkuId: "sku-yaskawa-sgm7j-04",
    tone: "#fff0e9",
    accent: "#ef846c",
    mark: "Σ7",
    badges: ["agreement", "promotion"],
    tags: ["伺服", "电机", "400W"],
    status: "active",
    isFeatured: true,
    createdAt: "2026-05-26T08:00:00.000Z",
    updatedAt: SKU_DATE,
    skus: [
      sku({
        id: "sku-yaskawa-sgm7j-04",
        productId: "prod-yaskawa-sgm7j",
        code: "SKU-YASK-SGM7J-04",
        name: "SGM7J-04A7A21 · 400 W",
        attributes: { 功率: "400 W", 编码器: "20-bit", 法兰: "80 mm" },
        unit: "台",
        price: 1280,
        listPrice: 1450,
        priceTiers: [
          { minQuantity: 1, unitPrice: 1280, label: "协议价" },
          { minQuantity: 5, unitPrice: 1228.8, label: "5+ 阶梯价" },
          { minQuantity: 10, unitPrice: 1177.6, label: "10+ 阶梯价" },
        ],
        stock: 58,
        availability: "preorder",
        leadTimeLabel: "预计 7–10 个工作日",
        weightKg: 2.4,
      }),
    ],
  },
  {
    id: "prod-siemens-3rv",
    slug: "siemens-3rv2011",
    title: "西门子电机保护断路器 3RV2011",
    subtitle: "0.63–1A · 螺钉端子",
    brand: "SIEMENS",
    categoryId: "electrical-components",
    category: "低压电器",
    description: "适用于三相电机过载及短路保护的紧凑型断路器。",
    unit: "件",
    defaultSkuId: "sku-siemens-3rv2011",
    tone: "#f2f0e8",
    accent: "#9b8b5b",
    mark: "SIE",
    badges: ["agreement", "new"],
    tags: ["断路器", "电机保护", "低压"],
    status: "active",
    isFeatured: false,
    createdAt: "2026-08-08T08:00:00.000Z",
    updatedAt: SKU_DATE,
    skus: [
      sku({
        id: "sku-siemens-3rv2011",
        productId: "prod-siemens-3rv2011",
        code: "SKU-SIE-3RV2011-1A",
        name: "3RV2011-1GA10 · 0.63–1 A",
        attributes: { 脱扣范围: "0.63–1 A", 极数: "3P", 端子: "螺钉" },
        unit: "件",
        price: 86.5,
        listPrice: 98,
        priceTiers: [
          { minQuantity: 1, unitPrice: 86.5, label: "协议价" },
          { minQuantity: 20, unitPrice: 82.18, label: "20+ 阶梯价" },
          { minQuantity: 50, unitPrice: 77.85, label: "50+ 阶梯价" },
        ],
        stock: 742,
        availability: "in_stock",
        leadTimeLabel: "现货 · 48 小时内发出",
        weightKg: 0.24,
      }),
    ],
  },
  {
    id: "prod-omron-g2r",
    slug: "omron-g2r-2-snd",
    title: "欧姆龙中间继电器 G2R-2-SND",
    subtitle: "24VDC · DPDT · 带 LED",
    brand: "OMRON",
    categoryId: "electrical-components",
    category: "继电器",
    description: "通用型中间继电器，带状态指示和锁定测试按钮。",
    unit: "只",
    defaultSkuId: "sku-omron-g2r-2",
    tone: "#f4ecf9",
    accent: "#9c71b6",
    mark: "OMR",
    badges: ["agreement", "spot", "bestseller"],
    tags: ["继电器", "24V", "控制元件"],
    status: "active",
    isFeatured: false,
    createdAt: "2026-04-21T08:00:00.000Z",
    updatedAt: SKU_DATE,
    skus: [
      sku({
        id: "sku-omron-g2r-2",
        productId: "prod-omron-g2r",
        code: "SKU-OMR-G2R-2-SND",
        name: "G2R-2-SND · 24VDC",
        attributes: { 线圈电压: "24 VDC", 触点: "DPDT", 指示: "LED" },
        unit: "只",
        price: 24.8,
        listPrice: 29.6,
        priceTiers: [
          { minQuantity: 1, unitPrice: 24.8, label: "协议价" },
          { minQuantity: 50, unitPrice: 23.31, label: "50+ 阶梯价" },
          { minQuantity: 200, unitPrice: 22.32, label: "200+ 阶梯价" },
        ],
        stock: 1920,
        availability: "in_stock",
        leadTimeLabel: "现货 · 24 小时内发出",
        weightKg: 0.07,
      }),
    ],
  },
  {
    id: "prod-3m-abrasive",
    slug: "3m-747d-abrasive",
    title: "3M 747D 砂带 100×610mm",
    subtitle: "P80 · 氧化铝磨料 · 10 条装",
    brand: "3M",
    categoryId: "tools-and-consumables",
    category: "生产耗材",
    description: "耐用型氧化铝砂带，适合不锈钢及碳钢表面打磨。",
    unit: "包",
    defaultSkuId: "sku-3m-747d-p80",
    tone: "#edf4eb",
    accent: "#60905f",
    mark: "3M",
    badges: ["promotion", "spot"],
    tags: ["砂带", "耗材", "P80"],
    status: "active",
    isFeatured: false,
    createdAt: "2026-08-22T08:00:00.000Z",
    updatedAt: SKU_DATE,
    skus: [
      sku({
        id: "sku-3m-747d-p80",
        productId: "prod-3m-abrasive",
        code: "SKU-3M-747D-P80",
        name: "747D · P80 · 10 条装",
        attributes: { 粒度: "P80", 尺寸: "100×610 mm", 包装: "10 条/包" },
        unit: "包",
        price: 118,
        listPrice: 136,
        priceTiers: [
          { minQuantity: 1, unitPrice: 118, label: "协议价" },
          { minQuantity: 10, unitPrice: 111.5, label: "10+ 阶梯价" },
          { minQuantity: 30, unitPrice: 106.2, label: "30+ 阶梯价" },
        ],
        stock: 284,
        availability: "in_stock",
        leadTimeLabel: "现货 · 48 小时内发出",
        weightKg: 0.55,
      }),
    ],
  },
];

export const MOCK_PROMOTIONS: Promotion[] = [
  {
    id: "promo-september-agreement",
    title: "金牌客户专享协议价",
    description: "已根据企业等级自动匹配，无需输入优惠码。",
    type: "percentage",
    scope: "catalogue",
    startsAt: "2026-01-01T00:00:00.000Z",
    endsAt: "2026-12-31T23:59:59.000Z",
    isActive: true,
    discountRate: 0.06,
    stackable: false,
    priority: 1,
  },
  {
    id: "promo-sensor-volume",
    title: "传感器批量采购优惠",
    description: "工业传感器满 10 件再享 4% 折扣。",
    type: "tier_price",
    scope: "category",
    categoryIds: ["industrial-automation"],
    startsAt: "2026-09-01T00:00:00.000Z",
    endsAt: "2026-09-30T23:59:59.000Z",
    isActive: true,
    minQuantity: 10,
    tiers: [{ minQuantity: 10, discountRate: 0.04 }, { minQuantity: 30, discountRate: 0.08 }],
    stackable: false,
    priority: 2,
  },
  {
    id: "promo-september-coupon",
    code: "NOVA50",
    title: "九月采购补贴",
    description: "订单满 ¥5,000 减 ¥50。",
    type: "coupon",
    scope: "cart",
    startsAt: "2026-09-01T00:00:00.000Z",
    endsAt: "2026-09-30T23:59:59.000Z",
    isActive: true,
    minSubtotal: 5000,
    discountAmount: 50,
    maxDiscount: 50,
    stackable: true,
    priority: 3,
  },
  {
    id: "promo-free-freight",
    title: "华南区域免运费",
    description: "订单满 ¥2,000，深圳仓配送免运费。",
    type: "free_shipping",
    scope: "cart",
    startsAt: "2026-09-01T00:00:00.000Z",
    endsAt: "2026-09-30T23:59:59.000Z",
    isActive: true,
    minSubtotal: 2000,
    stackable: true,
    priority: 5,
  },
];

export const MOCK_ADDRESSES: Address[] = [
  {
    id: "addr-shenzhen-factory",
    label: "深圳工厂（默认）",
    kind: "shipping",
    recipient: "陈志远",
    phone: "138****6721",
    province: "广东省",
    city: "深圳市",
    district: "宝安区",
    detail: "福海街道和平社区桥和路 18 号蓝图智造园 2 栋 1 楼",
    postalCode: "518103",
    isDefault: true,
  },
  {
    id: "addr-dongguan-warehouse",
    label: "东莞仓库",
    kind: "shipping",
    recipient: "周敏",
    phone: "139****2458",
    province: "广东省",
    city: "东莞市",
    district: "长安镇",
    detail: "乌沙社区振安东路 129 号 A 区仓储中心",
    postalCode: "523850",
    isDefault: false,
  },
  {
    id: "addr-hq-billing",
    label: "总部开票地址",
    kind: "billing",
    recipient: "林悦",
    phone: "0755-8234-1902",
    province: "广东省",
    city: "深圳市",
    district: "南山区",
    detail: "粤海街道科苑南路 2666 号中国华润大厦 20 层",
    postalCode: "518054",
    isDefault: true,
  },
];

export const MOCK_INVOICES: InvoiceProfile[] = [
  {
    id: "invoice-special-default",
    type: "vat_special",
    title: MOCK_COMPANY.name,
    taxId: MOCK_COMPANY.taxId,
    bankName: "招商银行深圳科技园支行",
    bankAccount: "7559 **** **** 8812",
    registeredAddress: "广东省深圳市南山区科技园",
    registeredPhone: "0755-8234-1902",
    receiveEmail: "finance@lantu-mfg.example",
    status: "active",
    isDefault: true,
  },
  {
    id: "invoice-normal-default",
    type: "vat_normal",
    title: MOCK_COMPANY.name,
    taxId: MOCK_COMPANY.taxId,
    receiveEmail: "finance@lantu-mfg.example",
    status: "active",
    isDefault: false,
  },
];

function createInitialCart(): Cart {
  const items = [
    createCartItem(MOCK_PRODUCTS[0], MOCK_PRODUCTS[0].skus[0], 12, SKU_DATE),
    createCartItem(MOCK_PRODUCTS[1], MOCK_PRODUCTS[1].skus[0], 2, SKU_DATE),
    createCartItem(MOCK_PRODUCTS[2], MOCK_PRODUCTS[2].skus[0], 1, SKU_DATE),
  ];
  return {
    id: "cart-lantu-default",
    companyId: MOCK_COMPANY.id,
    currency: "CNY",
    items,
    totals: calculateCartTotals(items).totals,
    updatedAt: SKU_DATE,
  };
}

export const MOCK_CART: Cart = createInitialCart();

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord-202609140012",
    orderNo: "PO202609140012",
    companyId: MOCK_COMPANY.id,
    createdBy: MOCK_USER.id,
    status: "pending_approval",
    approvalStatus: "pending",
    paymentMethod: "credit_account",
    lines: [
      {
        id: "line-202609140012-1",
        productId: MOCK_PRODUCTS[1].id,
        skuId: MOCK_PRODUCTS[1].skus[0].id,
        skuCode: MOCK_PRODUCTS[1].skus[0].code,
        productTitle: MOCK_PRODUCTS[1].title,
        skuName: MOCK_PRODUCTS[1].skus[0].name,
        attributes: MOCK_PRODUCTS[1].skus[0].attributes,
        unit: "件",
        quantity: 18,
        unitPrice: 156,
        listUnitPrice: 179,
        promotionDiscount: 0,
        subtotal: 2808,
      },
      {
        id: "line-202609140012-2",
        productId: MOCK_PRODUCTS[3].id,
        skuId: MOCK_PRODUCTS[3].skus[0].id,
        skuCode: MOCK_PRODUCTS[3].skus[0].code,
        productTitle: MOCK_PRODUCTS[3].title,
        skuName: MOCK_PRODUCTS[3].skus[0].name,
        attributes: MOCK_PRODUCTS[3].skus[0].attributes,
        unit: "件",
        quantity: 114,
        unitPrice: 86.5,
        listUnitPrice: 98,
        promotionDiscount: 0,
        subtotal: 9861,
      },
    ],
    totals: {
      currency: "CNY",
      subtotal: 12669,
      listSubtotal: 14322,
      promotionDiscount: 0,
      shippingFee: 0,
      tax: 0,
      total: 12669,
    },
    shippingAddress: {
      id: MOCK_ADDRESSES[0].id,
      label: MOCK_ADDRESSES[0].label,
      kind: MOCK_ADDRESSES[0].kind,
      recipient: MOCK_ADDRESSES[0].recipient,
      phone: MOCK_ADDRESSES[0].phone,
      province: MOCK_ADDRESSES[0].province,
      city: MOCK_ADDRESSES[0].city,
      district: MOCK_ADDRESSES[0].district,
      detail: MOCK_ADDRESSES[0].detail,
      postalCode: MOCK_ADDRESSES[0].postalCode,
    },
    invoice: {
      id: MOCK_INVOICES[0].id,
      type: MOCK_INVOICES[0].type,
      title: MOCK_INVOICES[0].title,
      taxId: MOCK_INVOICES[0].taxId,
      bankName: MOCK_INVOICES[0].bankName,
      bankAccount: MOCK_INVOICES[0].bankAccount,
      registeredAddress: MOCK_INVOICES[0].registeredAddress,
      registeredPhone: MOCK_INVOICES[0].registeredPhone,
      receiveEmail: MOCK_INVOICES[0].receiveEmail,
    },
    note: "请于工作日送货，入库前联系仓库。",
    createdAt: "2026-09-14T06:12:00.000Z",
    updatedAt: "2026-09-14T08:20:00.000Z",
    submittedAt: "2026-09-14T08:20:00.000Z",
  },
  {
    id: "ord-202609130087",
    orderNo: "PO202609130087",
    companyId: MOCK_COMPANY.id,
    createdBy: MOCK_USER.id,
    status: "processing",
    approvalStatus: "approved",
    paymentMethod: "credit_account",
    lines: [
      {
        id: "line-202609130087-1",
        productId: MOCK_PRODUCTS[0].id,
        skuId: MOCK_PRODUCTS[0].skus[0].id,
        skuCode: MOCK_PRODUCTS[0].skus[0].code,
        productTitle: MOCK_PRODUCTS[0].title,
        skuName: MOCK_PRODUCTS[0].skus[0].name,
        attributes: MOCK_PRODUCTS[0].skus[0].attributes,
        unit: "个",
        quantity: 120,
        unitPrice: 16.74,
        listUnitPrice: 22.4,
        promotionDiscount: 0,
        subtotal: 2008.8,
      },
    ],
    totals: {
      currency: "CNY",
      subtotal: 2008.8,
      listSubtotal: 2688,
      promotionDiscount: 0,
      shippingFee: 0,
      tax: 0,
      total: 2008.8,
    },
    shippingAddress: {
      id: MOCK_ADDRESSES[0].id,
      label: MOCK_ADDRESSES[0].label,
      kind: MOCK_ADDRESSES[0].kind,
      recipient: MOCK_ADDRESSES[0].recipient,
      phone: MOCK_ADDRESSES[0].phone,
      province: MOCK_ADDRESSES[0].province,
      city: MOCK_ADDRESSES[0].city,
      district: MOCK_ADDRESSES[0].district,
      detail: MOCK_ADDRESSES[0].detail,
      postalCode: MOCK_ADDRESSES[0].postalCode,
    },
    createdAt: "2026-09-13T03:45:00.000Z",
    updatedAt: "2026-09-13T08:10:00.000Z",
    submittedAt: "2026-09-13T04:10:00.000Z",
  },
  {
    id: "ord-202609080031",
    orderNo: "PO202609080031",
    companyId: MOCK_COMPANY.id,
    createdBy: MOCK_USER.id,
    status: "completed",
    approvalStatus: "approved",
    paymentMethod: "bank_transfer",
    lines: [
      {
        id: "line-202609080031-1",
        productId: MOCK_PRODUCTS[4].id,
        skuId: MOCK_PRODUCTS[4].skus[0].id,
        skuCode: MOCK_PRODUCTS[4].skus[0].code,
        productTitle: MOCK_PRODUCTS[4].title,
        skuName: MOCK_PRODUCTS[4].skus[0].name,
        attributes: MOCK_PRODUCTS[4].skus[0].attributes,
        unit: "只",
        quantity: 200,
        unitPrice: 22.32,
        listUnitPrice: 29.6,
        promotionDiscount: 0,
        subtotal: 4464,
      },
    ],
    totals: {
      currency: "CNY",
      subtotal: 4464,
      listSubtotal: 5920,
      promotionDiscount: 0,
      shippingFee: 0,
      tax: 0,
      total: 4464,
    },
    shippingAddress: {
      id: MOCK_ADDRESSES[1].id,
      label: MOCK_ADDRESSES[1].label,
      kind: MOCK_ADDRESSES[1].kind,
      recipient: MOCK_ADDRESSES[1].recipient,
      phone: MOCK_ADDRESSES[1].phone,
      province: MOCK_ADDRESSES[1].province,
      city: MOCK_ADDRESSES[1].city,
      district: MOCK_ADDRESSES[1].district,
      detail: MOCK_ADDRESSES[1].detail,
      postalCode: MOCK_ADDRESSES[1].postalCode,
    },
    createdAt: "2026-09-08T09:05:00.000Z",
    updatedAt: "2026-09-12T10:20:00.000Z",
    submittedAt: "2026-09-08T09:15:00.000Z",
    paidAt: "2026-09-08T10:00:00.000Z",
    shippedAt: "2026-09-10T02:30:00.000Z",
    completedAt: "2026-09-12T10:20:00.000Z",
  },
];

/** Lower-case aliases make the fixtures pleasant to consume in components. */
export const mockCategories = MOCK_CATEGORIES;
export const mockCompany = MOCK_COMPANY;
export const mockUser = MOCK_USER;
export const mockProducts = MOCK_PRODUCTS;
export const mockPromotions = MOCK_PROMOTIONS;
export const mockAddresses = MOCK_ADDRESSES;
export const mockInvoices = MOCK_INVOICES;
export const mockCart = MOCK_CART;
export const mockOrders = MOCK_ORDERS;

export const products = MOCK_PRODUCTS;
export const promotions = MOCK_PROMOTIONS;
export const addresses = MOCK_ADDRESSES;
export const invoices = MOCK_INVOICES;
export const orders = MOCK_ORDERS;

// Names used by the feature modules; aliases keep the fixture source of truth
// singular while allowing either naming convention at call sites.
export const categories = MOCK_CATEGORIES;
export const companyProfile = MOCK_COMPANY;
export const currentUser = MOCK_USER;
export const invoiceProfiles = MOCK_INVOICES;
export const seedOrders = MOCK_ORDERS;
