"use client";

import Link from "next/link";
import { useState } from "react";
import { AppShell } from "./components/app-shell";
import { Icon } from "./components/icons";
import { ProductCard } from "./components/product-card";
import { useStore } from "./components/store-provider";
import { Button, Eyebrow, Money, SectionHeading, cn } from "./components/ui";
import { formatDate, getDefaultSku, isPromotionActive } from "./lib/domain";

export default function HomePage() {
  const { products, categories, promotions, orders, company, addToCart } = useStore();
  const [search, setSearch] = useState("");
  const featured = products.filter((product) => product.isFeatured).slice(0, 3);
  const activePromotion = promotions.find((promotion) => isPromotionActive(promotion));

  function submitSearch(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const value = search.trim();
    const destination = /^(PO|ord_)/i.test(value) ? "/orders" : "/products";
    window.location.href = value ? `${destination}?query=${encodeURIComponent(value)}` : destination;
  }

  return <AppShell>
    <div className="space-y-8">
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div><div className="flex items-center gap-2 text-[11px] text-slate-400"><span>采购空间</span><Icon name="chevron" size={12} /><span className="font-bold text-ink">商城首页</span></div><h1 className="mt-3 text-[28px] font-black tracking-[-0.05em] text-ink sm:text-[34px]">把采购做得更快、更稳 <span className="ml-1 inline-block">✦</span></h1><p className="mt-2 text-[12px] text-slate">早上好，{company.shortName}。协议价已自动匹配，今天也从一份清晰的采购清单开始。</p></div>
        <div className="flex items-center gap-2"><Link href="/orders" className="hidden text-[11px] font-bold text-slate transition hover:text-cyan sm:block">查看最近订单 <Icon name="arrow" size={13} className="ml-1 inline" /></Link><Link href="/products"><Button variant="primary"><Icon name="bag" size={15} />开始选品</Button></Link></div>
      </div>

      <section className="relative overflow-hidden rounded-[26px] bg-[#10233f] px-6 py-8 text-white shadow-[0_18px_45px_rgba(16,35,63,0.16)] sm:px-10 sm:py-10">
        <div className="absolute -right-20 -top-32 h-[360px] w-[360px] rounded-full border-[50px] border-[#ff745f]/15" /><div className="absolute -bottom-40 right-[26%] h-[300px] w-[300px] rounded-full border-[26px] border-cyan/10" /><div className="absolute right-[17%] top-12 hidden h-3 w-3 rounded-full bg-[#ffcf70] shadow-[0_0_0_7px_rgba(255,207,112,0.1)] lg:block" />
        <div className="relative max-w-[660px]"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-white/10 px-3 py-1.5 text-[10px] font-bold text-[#a1eee8]"><Icon name="shield" size={12} className="mr-1 inline" />金牌企业专属空间</span><span className="text-[10px] text-white/55">协议价 · 30 天账期 · 专属服务</span></div><h2 className="mt-5 text-[25px] font-black tracking-[-0.04em] sm:text-[32px]">今天想采购什么？</h2><p className="mt-2 max-w-[500px] text-[12px] leading-6 text-white/65">从可信赖的品牌商品，到随时可查的订单状态。把复杂采购，交给一个更清晰的工作台。</p>
          <form onSubmit={submitSearch} className="mt-6 flex max-w-[560px] items-center gap-2 rounded-2xl bg-white p-1.5 shadow-[0_10px_25px_rgba(0,0,0,0.15)]"><div className="flex min-w-0 flex-1 items-center gap-2 px-3"><Icon name="search" size={17} className="shrink-0 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} className="h-10 min-w-0 flex-1 border-0 bg-transparent text-[12px] text-ink outline-none placeholder:text-slate-400" placeholder="搜索商品名称、品牌、SKU 或订单号" aria-label="搜索商品、品牌、SKU 或订单号" /></div><button type="submit" className="flex h-10 shrink-0 items-center gap-2 rounded-xl bg-coral px-4 text-[11px] font-bold text-white transition hover:bg-[#e96350]"><span className="hidden sm:inline">搜索</span><Icon name="arrow" size={15} /></button></form>
        </div>
        <div className="relative mt-8 grid max-w-[650px] grid-cols-3 gap-4 border-t border-white/10 pt-5 sm:absolute sm:bottom-10 sm:right-10 sm:mt-0 sm:w-[370px] sm:border-0 sm:pt-0"><div><div className="text-[20px] font-black tracking-[-0.04em]">{categories.reduce((sum, item) => sum + (item.productCount ?? 0), 0)}+</div><div className="mt-1 text-[10px] text-white/55">可采购商品（演示）</div></div><div><div className="text-[20px] font-black tracking-[-0.04em]">{company.paymentTermDays} 天</div><div className="mt-1 text-[10px] text-white/55">企业账期</div></div><div><div className="text-[20px] font-black tracking-[-0.04em]">{(company.creditLimit - company.creditUsed).toLocaleString("zh-CN")}</div><div className="mt-1 text-[10px] text-white/55">演示授信余额</div></div></div>
      </section>

      <section><SectionHeading eyebrow="BROWSE BY CATEGORY" title="按采购场景选品" description="从高频品类开始，协议价与库存状态一目了然" action={<Link href="/products" className="text-[11px] font-bold text-cyan hover:text-ink">查看全部 <Icon name="arrow" size={13} className="ml-1 inline" /></Link>} /><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{categories.map((category, index) => { const colors = [{ bg: "#e9f8f5", icon: "#139992" }, { bg: "#edf1fc", icon: "#5b78c0" }, { bg: "#fff1e9", icon: "#df765a" }, { bg: "#f3edfb", icon: "#956ec0" }, { bg: "#fff8df", icon: "#b38827" }]; const color = colors[index % colors.length]; return <Link key={category.id} href={`/products?category=${category.id}`} className="group rounded-2xl border border-line bg-white p-4 transition hover:-translate-y-0.5 hover:border-cyan/30 hover:shadow-soft"><span className="flex h-10 w-10 items-center justify-center rounded-xl text-[17px] font-black" style={{ background: color.bg, color: color.icon }}>{["◈", "⌁", "▦", "◌", "✚"][index]}</span><div className="mt-3 truncate text-[12px] font-bold text-ink group-hover:text-cyan">{category.name}</div><div className="mt-1 text-[10px] text-slate">{category.productCount} 个可采购商品</div></Link>; })}</div></section>

      {activePromotion && <section className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_300px]"><div className="relative overflow-hidden rounded-[23px] bg-[#fff0e9] px-6 py-6 sm:px-8"><div className="absolute -right-8 -top-10 h-40 w-40 rounded-full border-[22px] border-[#ff9c83]/25" /><div className="relative max-w-[620px]"><span className="rounded-full bg-white/70 px-2.5 py-1 text-[10px] font-bold text-[#bd644d]">SEPTEMBER PICKS · 限时活动</span><h2 className="mt-4 text-[22px] font-black tracking-[-0.04em] text-[#7d4032] sm:text-[25px]">批量采购，价格再往下走一步</h2><p className="mt-2 text-[11px] leading-5 text-[#9c6555]">{activePromotion.description} 协议价已生效，满足数量门槛后自动计算。</p><Link href="/promotions" className="mt-5 inline-flex items-center gap-2 text-[11px] font-black text-[#c25f47]">查看全部活动 <Icon name="arrow" size={14} /></Link></div></div><div className="rounded-[23px] bg-[#e6f7f4] p-6"><div className="flex items-start justify-between"><div><Eyebrow className="text-[#4a9892]">YOUR BENEFIT</Eyebrow><div className="mt-3 text-[27px] font-black tracking-[-0.05em] text-[#146e70]">已匹配</div><div className="mt-1 text-[11px] font-semibold text-[#4a8986]">企业专属协议价</div></div><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white text-cyan"><Icon name="percent" size={18} /></span></div><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-white/80"><div className="h-full w-full rounded-full bg-cyan" /></div><div className="mt-2 flex justify-between text-[9px] text-[#4a8986]"><span>价格与交期透明展示</span><span>含税</span></div></div></section>}

      <section><SectionHeading eyebrow="RECOMMENDED FOR YOU" title="企业热销商品" description="基于你的采购偏好与企业协议，优先推荐高频 SKU" action={<Link href="/products" className="text-[11px] font-bold text-cyan hover:text-ink">进入商品目录 <Icon name="arrow" size={13} className="ml-1 inline" /></Link>} /><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{featured.map((product) => <ProductCard key={product.id} product={product} onAdd={(item, quantity) => addToCart(item.id, getDefaultSku(item).id, quantity)} />)}</div></section>

      <section className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-line px-5 py-5 sm:px-6"><div><Eyebrow>RECENT ORDERS</Eyebrow><h2 className="mt-1.5 text-[17px] font-black text-ink">最近订单</h2></div><Link href="/orders" className="text-[11px] font-bold text-cyan">查看全部 <Icon name="arrow" size={13} className="ml-1 inline" /></Link></div><div className="divide-y divide-line">{orders.slice(0, 3).map((order) => <Link href={`/orders/${order.id}`} key={order.id} className="flex items-center gap-4 px-5 py-4 transition hover:bg-fog sm:px-6"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#edf1fc] text-[#5b78c0]"><Icon name={order.status === "completed" ? "check" : order.status === "processing" ? "truck" : "clock"} size={17} /></span><span className="min-w-0 flex-1"><span className="block truncate text-[12px] font-bold text-ink">{order.orderNo}</span><span className="mt-1 block truncate text-[10px] text-slate">{order.lines[0]?.productTitle}{order.lines.length > 1 ? ` 等 ${order.lines.length} 项` : ""}</span></span><span className="hidden text-right sm:block"><span className="block text-[12px] font-black text-ink"><Money value={order.totals.total} /></span><span className="mt-1 block text-[10px] text-slate">{formatDate(order.createdAt, false)}</span></span><Icon name="chevron" size={15} className="text-slate-300" /></Link>)}</div></div><div className="rounded-2xl bg-[#10233f] p-6 text-white"><div className="flex items-start justify-between"><div><Eyebrow className="text-white/45">PROCUREMENT CARE</Eyebrow><h2 className="mt-2 text-[19px] font-black tracking-[-0.03em]">有一份清单，<br />我们帮你更快完成。</h2></div><Icon name="spark" size={25} className="text-[#ffcf70]" /></div><p className="mt-4 text-[11px] leading-5 text-white/60">批量粘贴 SKU 和数量，系统自动匹配协议价、库存和交期。</p><Link href="/products" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-white px-3.5 py-2.5 text-[10px] font-black text-ink transition hover:bg-[#dff8f5]">去逛逛商品目录 <Icon name="arrow" size={14} /></Link></div></section>
    </div>
  </AppShell>;
}
