"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { AppShell } from "../../components/app-shell";
import { Icon } from "../../components/icons";
import { useStore } from "../../components/store-provider";
import { Button, Breadcrumbs, EmptyState, Money, ProductVisual, QuantityStepper, SectionHeading, cn } from "../../components/ui";
import { getDefaultSku, getTierUnitPrice } from "../../lib/domain";

export default function ProductDetailPage() {
  const params = useParams<{ id: string }>();
  const router = useRouter();
  const { products, addToCart } = useStore();
  const product = products.find((item) => item.id === params.id || item.slug === params.id);
  const [selectedSkuId, setSelectedSkuId] = useState(product?.defaultSkuId ?? "");
  const [quantity, setQuantity] = useState(1);

  const sku = product?.skus.find((item) => item.id === selectedSkuId) ?? (product ? getDefaultSku(product) : undefined);
  const unitPrice = useMemo(() => sku ? getTierUnitPrice(sku, quantity) : 0, [sku, quantity]);

  if (!product || !sku) return <AppShell><EmptyState icon="package" title="商品不存在或已下架" description="请返回商品目录，浏览当前可采购的商品。" action={<Link href="/products"><Button>返回商品目录</Button></Link>} /></AppShell>;

  return <AppShell><div className="space-y-6"><Breadcrumbs items={["商品目录", product.category, product.title]} /><div className="grid gap-6 lg:grid-cols-[minmax(0,0.95fr)_minmax(0,1.05fr)]"><section className="panel p-4 sm:p-5"><ProductVisual tone={product.tone} accent={product.accent} mark={product.mark} large /><div className="mt-4 flex flex-wrap gap-2">{product.badges.includes("agreement") && <span className="rounded-full bg-cyan/10 px-2.5 py-1 text-[10px] font-bold text-[#118c87]">企业协议价</span>}{product.badges.includes("promotion") && <span className="rounded-full bg-[#fff0e6] px-2.5 py-1 text-[10px] font-bold text-[#cf6b43]">限时促销</span>}<span className="rounded-full bg-fog px-2.5 py-1 text-[10px] font-bold text-slate">{product.brand}</span></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{Object.entries(sku.attributes).map(([key, value]) => <div key={key} className="rounded-xl bg-fog px-3 py-3"><div className="text-[10px] text-slate-400">{key}</div><div className="mt-1 text-[11px] font-bold text-ink">{value}</div></div>)}</div></section>
      <section className="min-w-0"><div className="flex items-center gap-2 text-[10px] font-bold text-cyan"><Icon name="shield" size={14} />金牌客户专享协议</div><h1 className="mt-3 text-[29px] font-black leading-tight tracking-[-0.05em] text-ink sm:text-[35px]">{product.title}</h1><p className="mt-2 text-[13px] text-slate">{product.subtitle}</p><p className="mt-5 max-w-[650px] text-[12px] leading-6 text-slate">{product.description}</p><div className="mt-6 rounded-2xl bg-[#f1fbfa] p-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-[10px] font-semibold text-[#4f9893]">当前企业价 / {sku.unit} · 含税</div><div className="mt-1 flex items-baseline gap-2"><Money value={unitPrice} className="text-[32px] font-black tracking-[-0.06em] text-ink" /><span className="text-[12px] text-slate-400 line-through"><Money value={sku.listPrice ?? unitPrice} /></span></div></div><div className="text-right"><div className={cn("text-[11px] font-bold", sku.availability === "low_stock" ? "text-coral" : "text-[#168f88]")}><span className="mr-1 inline-block h-1.5 w-1.5 rounded-full bg-current" />{sku.stock.toLocaleString("zh-CN")} {sku.unit} 可售</div><div className="mt-1 text-[10px] text-slate">{sku.leadTimeLabel}</div></div></div><div className="mt-5 grid grid-cols-3 overflow-hidden rounded-xl border border-[#d5eeeb] bg-white">{sku.priceTiers.map((tier) => <div key={tier.minQuantity} className="border-r border-[#d5eeeb] px-3 py-3 last:border-r-0"><div className="text-[10px] text-slate">≥ {tier.minQuantity} {sku.unit}</div><div className="mt-1 text-[13px] font-black text-ink"><Money value={tier.unitPrice} /></div></div>)}</div></div>
        {product.skus.length > 1 && <div className="mt-6"><div className="mb-2 text-[11px] font-bold text-ink">规格选择</div><div className="flex flex-wrap gap-2">{product.skus.map((item) => <button type="button" key={item.id} onClick={() => setSelectedSkuId(item.id)} className={cn("rounded-xl border px-3 py-2 text-[11px] font-bold", selectedSkuId === item.id ? "border-cyan bg-cyan/10 text-[#128c87]" : "border-line bg-white text-slate")}>{item.name}</button>)}</div></div>}
        <div className="mt-6 flex flex-wrap items-end gap-4"><div><div className="mb-2 text-[11px] font-bold text-ink">采购数量 <span className="ml-1 font-normal text-slate">起订 1 {sku.unit}</span></div><QuantityStepper value={quantity} onChange={setQuantity} min={1} max={sku.stock} /></div><div className="flex flex-1 gap-2 sm:flex-none"><Button variant="soft" onClick={() => addToCart(product.id, sku.id, quantity)} className="h-10 flex-1 sm:w-[170px]"><Icon name="cart" size={16} />加入采购车</Button><Button onClick={() => { addToCart(product.id, sku.id, quantity); router.push("/cart"); }} className="h-10 flex-1 sm:w-[170px]">立即结算 <Icon name="arrow" size={15} /></Button></div></div>
        <div className="mt-7 grid gap-3 border-t border-line pt-5 sm:grid-cols-3"><div className="flex items-center gap-2 text-[10px] text-slate"><Icon name="shield" size={15} className="text-cyan" />企业协议价保障</div><div className="flex items-center gap-2 text-[10px] text-slate"><Icon name="truck" size={15} className="text-cyan" />透明交期与配送</div><div className="flex items-center gap-2 text-[10px] text-slate"><Icon name="receipt" size={15} className="text-cyan" />可开增值税专票</div></div></section></div>
      <section className="panel p-5 sm:p-6"><SectionHeading eyebrow="PRODUCT NOTES" title="采购说明" description="下单前快速了解商品和价格规则" /><div className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-fog p-4"><Icon name="layers" size={19} className="text-cyan" /><h3 className="mt-3 text-[12px] font-bold text-ink">阶梯价自动生效</h3><p className="mt-2 text-[10px] leading-5 text-slate">调整数量后，系统会在结算时按当前企业协议重新计算价格。</p></div><div className="rounded-2xl bg-fog p-4"><Icon name="clock" size={19} className="text-[#d88962]" /><h3 className="mt-3 text-[12px] font-bold text-ink">交期以提交时为准</h3><p className="mt-2 text-[10px] leading-5 text-slate">库存和交期可能变化，结算页会再次校验并提示异常。</p></div><div className="rounded-2xl bg-fog p-4"><Icon name="file" size={19} className="text-[#6d80c1]" /><h3 className="mt-3 text-[12px] font-bold text-ink">订单保留商品快照</h3><p className="mt-2 text-[10px] leading-5 text-slate">提交后的商品名称、规格和价格会固定在订单里，便于对账。</p></div></div></section>
    </div></AppShell>;
}
