"use client";

import Link from "next/link";
import { AppShell } from "../components/app-shell";
import { Icon } from "../components/icons";
import { ProductCard } from "../components/product-card";
import { useStore } from "../components/store-provider";
import { Button, Eyebrow, SectionHeading, cn } from "../components/ui";
import { formatDate, isPromotionActive } from "../lib/domain";

export default function PromotionsPage() {
  const { promotions, products, addToCart } = useStore();
  const featuredProducts = products.filter((product) => product.badges.includes("promotion")).slice(0, 3);
  return <AppShell><div className="space-y-7"><div className="flex items-center gap-2 text-[11px] text-slate-400"><span>采购空间</span><Icon name="chevron" size={12} /><span className="font-bold text-ink">促销活动</span></div><div><h1 className="text-[29px] font-black tracking-[-0.05em] text-ink">促销活动</h1><p className="mt-2 text-[12px] text-slate">协议价之外，再为你的采购计划争取一点空间。</p></div><section className="relative overflow-hidden rounded-[26px] bg-[#10233f] px-6 py-8 text-white sm:px-10 sm:py-10"><div className="absolute -right-12 -top-16 h-56 w-56 rounded-full border-[30px] border-[#ff745f]/20" /><div className="absolute bottom-[-110px] right-[28%] h-64 w-64 rounded-full border-[25px] border-cyan/10" /><div className="relative max-w-[680px]"><span className="rounded-full bg-[#ff745f]/20 px-3 py-1.5 text-[10px] font-bold text-[#ffb3a2]">SEASONAL CAMPAIGN · 09.01 — 09.30</span><h2 className="mt-5 text-[26px] font-black tracking-[-0.05em] sm:text-[33px]">九月采购季，<br />让每一次批量都更有价值。</h2><p className="mt-3 max-w-[520px] text-[12px] leading-6 text-white/60">企业协议价、批量阶梯价和活动补贴会在结算时自动校验。无需记住规则，把清单交给我们。</p><Link href="/products" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[#ff745f] px-4 py-3 text-[11px] font-black text-white transition hover:bg-[#eb654f]">去逛活动商品 <Icon name="arrow" size={15} /></Link></div></section>
    <section><SectionHeading eyebrow="ACTIVE NOW" title="正在进行的优惠" description="同一订单最多叠加一条活动规则，最终以结算校验为准" /><div className="mt-4 grid gap-4 md:grid-cols-2">{promotions.filter((promotion) => isPromotionActive(promotion)).map((promotion, index) => <article key={promotion.id} className={cn("relative overflow-hidden rounded-[22px] border p-5 sm:p-6", index % 2 === 0 ? "border-[#f5d9d0] bg-[#fff5f1]" : "border-[#d5eeeb] bg-[#f1fbfa]")}><div className="absolute -right-9 -top-9 h-28 w-28 rounded-full border-[15px] opacity-50" style={{ borderColor: index % 2 === 0 ? "#ffb7a5" : "#8adfd7" }} /><div className="relative flex items-start justify-between gap-3"><div><span className={cn("rounded-full px-2.5 py-1 text-[9px] font-black", index % 2 === 0 ? "bg-white/80 text-[#bd624b]" : "bg-white/80 text-[#25827b]")}>{promotion.type === "percentage" ? "协议权益" : promotion.type === "tier_price" ? "阶梯优惠" : promotion.type === "coupon" ? "采购补贴" : "配送权益"}</span><h3 className="mt-4 text-[17px] font-black tracking-[-0.03em] text-ink">{promotion.title}</h3><p className="mt-2 max-w-[420px] text-[11px] leading-5 text-slate">{promotion.description}</p></div><Icon name={promotion.type === "free_shipping" ? "truck" : "percent"} size={25} className={index % 2 === 0 ? "text-coral" : "text-cyan"} /></div><div className="relative mt-6 flex items-center justify-between border-t border-black/5 pt-4"><div className="flex items-center gap-1.5 text-[10px] text-slate"><Icon name="calendar" size={13} />有效期至 {formatDate(promotion.endsAt)}</div><Link href="/products" className="text-[10px] font-black text-cyan">去选商品 <Icon name="arrow" size={13} className="ml-1 inline" /></Link></div></article>)}</div></section>
    <section><SectionHeading eyebrow="PROMOTION PICKS" title="活动商品精选" description="适合本月集中采购的高频 SKU" /><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{featuredProducts.map((product) => <ProductCard key={product.id} product={product} onAdd={(item, quantity) => addToCart(item.id, item.defaultSkuId, quantity)} />)}</div></section>
    <section className="rounded-2xl border border-line bg-white p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><Eyebrow>PROMOTION RULE</Eyebrow><h2 className="mt-2 text-[17px] font-black text-ink">价格怎么算？</h2><p className="mt-2 max-w-[670px] text-[11px] leading-5 text-slate">企业协议价作为基价，满足活动条件后自动计算一条活动优惠；购物车停留期间如果价格、库存或活动窗口发生变化，结算页会再次校验并提示。</p></div><Link href="/cart"><Button variant="soft">查看采购车 <Icon name="arrow" size={14} /></Button></Link></div></section>
  </div></AppShell>;
}
